/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "FitnessApp": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
    "PersonalSite": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
  }
}

import "sst"
export {}